##############################
### ARTIFACT ROUTE TESTING ###
##############################

### List all artifacts 
GET http://localhost:3000/artifacts


### Find a particular artifact with a given id
GET http://localhost:3000/artifacts/2

### Create a new artifact
POST http://localhost:3000/artifacts/create
Content-Type: application/json

{   
    "name": "Artifact 1",
    "blurb": "This is a blurb about artifact 1"
}

### Delete an artifact with a given id
DELETE http://localhost:3000/artifacts/1

### Update an artifact with a given id
PATCH http://localhost:3000/artifacts/2
Content-Type: application/json

{
    "name": "Artifact 1",
    "blurb": "This is a blurb about artifact 1"
}

### Approve an artifact with a given id
PATCH http://localhost:3000/artifacts/2/approve
Content-Type: application/json

{
    "approved": true
}

##############################
###  ARTIST ROUTE TESTING  ###
##############################

### List all artists
GET http://localhost:3000/artists

### Find a particular artist with a given id
GET http://localhost:3000/artists/3

### Create a new artist
POST http://localhost:3000/artists/create
Content-Type: application/json

{
    "name": "Artist 1",
    "blurb": "This is a blurb about artist 1",
    "company": "Company 1",
    "title": "Title 1"
}

### Approve an artist with a given id
PATCH http://localhost:3000/artists/2/approve
Content-Type: application/json

{
    "approved": true
}

### Update an artist with a given id
PATCH http://localhost:3000/artists/1
Content-Type: application/json

{
    "name": "Artist 2",
    "blurb": "This is a blurb about artist 2",
    "company": "Company 2",
    "title": "Title 3"
}

### Delete an artist with a given id
DELETE http://localhost:3000/artists/2


##############################
###   USER ROUTE TESTING   ###
##############################

### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "daisy@hotmail.com",
    "password": "password",
    "admin": true
}

### Sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "daisy@hotmail.com",
    "password": "password"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out the currently signed in user
POST http://localhost:3000/auth/signout

### Find a particular user with a given id
GET http://localhost:3000/auth/3

### Find all users with a particular email
GET http://localhost:3000/auth?email=delly@gmail.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/1

### Update a user with a given id
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "delly@hotmail.com",
    "password": "password",
    "admin": true
}